version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
    - 1.11.0
    - 1.11.2
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-bootstrap
    versions:
    - 4.6.2
  - dependency-name: ember-cli-update
    versions:
    - 0.55.2
  - dependency-name: ember-prism
    versions:
    - 0.9.0
  - dependency-name: ember-angle-bracket-invocation-polyfill
    versions:
    - 3.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
